/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package despertador;

import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author vit
 */
public class despertar extends javax.swing.JFrame implements Runnable{
Thread hilo1;
int c1=0;
    /**
     * Creates new form despertar
     */
    public despertar() {
        initComponents();
        
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        
      
       this.Hora.setText(hour.format(now));
//       cbhora();
    hilo1 = new Thread(this);
         hilo1.start();
    }
    /*public void cbhora(){
    
    
    for(int a= 0;a<=24;a++){
        for(int b= 0;b<=60;b=b+5){
            
                CBHora.addItem(a+":"+b+":00");
    
    }
    }
    
    
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Alarma = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TexAlarma = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jLabel1.setText("Hora:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        jLabel2.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jLabel2.setText("Alarma:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, -1, -1));

        Hora.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        Hora.setText("         ");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 63, 289, -1));

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Despertador");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 400, 40));

        Alarma.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        Alarma.setText("Esperando Hora...");
        getContentPane().add(Alarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 98, 275, -1));

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jButton2.setText("Alarma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, 35));

        TexAlarma.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        getContentPane().add(TexAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 138, 199, -1));

        jButton3.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 32));

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyTyped(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jCheckBox2.setText("jCheckBox2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jCheckBox3.setText("jCheckBox3");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jCheckBox4.setText("jCheckBox4");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String horas (){

Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        
        String hor = hour.format(now);
        return hor;
}




    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
       Alarma.setText(TexAlarma.getText());
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
//     Alarma.setText((String) CBHora.getSelectedItem());
     
     Despertador.pl.close();
   
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1KeyTyped
public void correr (){
c1++;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(despertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(despertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(despertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(despertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new despertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alarma;
    private javax.swing.JLabel Hora;
    private javax.swing.JTextField TexAlarma;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    
    
    public void run() {
      
        Thread ct= Thread.currentThread();
        
        while(ct==hilo1){
        correr();
        Hora.setText(horas());
            System.out.println("la hora es: "+horas());
            
            if(Alarma.getText().equals(horas())){
            System.out.println("despertador.despertar.Accionado");
            try {
                Despertador.despertado();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(despertar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JavaLayerException ex) {
                Logger.getLogger(despertar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(despertar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        }
        throw new UnsupportedOperationException("not supported yet");
    }
}
